#!/usr/bin/env bun

/**
 * One-time port of CyberStrike's web pentest skills + scanners into OMP's
 * in-source `packages/coding-agent/src/pentest` layout (non-recursive,
 * `hide: true`, verbatim bodies).
 *
 * Source: CyberStrike repo (AGPL-3.0-only) — ported content must NOT be
 * upstreamed into can1357/oh-my-pi without relicensing. See
 * `packages/coding-agent/src/pentest/ATTRIBUTION.md` generated by this script.
 *
 * Usage:
 *   bun scripts/port-cyberstrike-skills.ts --src <CyberStrikeRepo>/.cyberstrike/skill --dst <OmpRepo>/packages/coding-agent/src/pentest/skills
 *
 * `--dst` is the SKILLS directory; the pentest root is derived as its parent
 * (scanners → <root>/scanners, INDEX.md/ATTRIBUTION.md → <root>).
 * No deps beyond node builtins. Frontmatter is patched line-wise (keys are
 * single-line scalars in the source); everything unknown is preserved verbatim.
 */

import { execSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";

const HELP = `Usage: bun scripts/port-cyberstrike-skills.ts --src <dir> --dst <dir>

Ports CyberStrike web pentest skills (WEB/OWASP_WSTG_4.2, attack-*, recon-methodology)
and the 16 attack scanners into OMP's in-source packages/coding-agent/src/pentest layout.

Options:
  --src <dir>   CyberStrike .cyberstrike/skill directory (source of truth)
  --dst <dir>   Destination src/pentest/skills directory (created if absent);
                the pentest root (scanners/, INDEX.md, ATTRIBUTION.md) is its parent
  -h, --help    Show this help
`;

function optionValue(argv: readonly string[], index: number, name: string): { value: string; nextIndex: number } {
	const inlinePrefix = `${name}=`;
	const current = argv[index] ?? "";
	if (current.startsWith(inlinePrefix)) return { value: current.slice(inlinePrefix.length), nextIndex: index };
	const value = argv[index + 1];
	if (!value || value.startsWith("--")) throw new Error(`${name} requires a value`);
	return { value, nextIndex: index + 1 };
}

function parseArgs(argv: readonly string[]): { src: string; dst: string } {
	let src = "";
	let dst = "";
	for (let i = 0; i < argv.length; i++) {
		const arg = argv[i];
		if (arg === "-h" || arg === "--help") {
			console.log(HELP);
			process.exit(0);
		} else if (arg === "--src") {
			const r = optionValue(argv, i, "--src");
			src = r.value;
			i = r.nextIndex;
		} else if (arg.startsWith("--src=")) {
			src = arg.slice("--src=".length);
		} else if (arg === "--dst") {
			const r = optionValue(argv, i, "--dst");
			dst = r.value;
			i = r.nextIndex;
		} else if (arg.startsWith("--dst=")) {
			dst = arg.slice("--dst=".length);
		} else {
			throw new Error(`unknown argument: ${arg}`);
		}
	}
	if (!src || !dst) throw new Error("both --src and --dst are required");
	if (!existsSync(src)) throw new Error(`--src does not exist: ${src}`);
	return { src, dst };
}

const SCANNER_NAMES = [
	"cloud_storage_enum",
	"cors_checker",
	"file_upload_tester",
	"github_dorker",
	"graphql_tester",
	"idor_tester",
	"jwt_tamper",
	"oauth_tester",
	"race_tester",
	"rate_limit_bypass",
	"response_diff",
	"ssrf_listener",
	"ssti_tester",
	"subdomain_takeover",
	"waf_bypass",
	"wayback_endpoints",
];

interface PortedSkill {
	name: string;
	description: string;
	dir: string;
	category: string;
	owaspId: string;
	sourceRel: string;
	extraFiles: string[];
}

function detectEol(content: string): string {
	return content.includes("\r\n") ? "\r\n" : "\n";
}

function splitFrontmatter(content: string): { frontmatter: string; body: string; error?: string; eol: string } {
	const eol = detectEol(content);
	const open = `---${eol}`;
	const close = `${eol}---${eol}`;
	if (!content.startsWith(open)) return { frontmatter: "", body: content, error: "no leading --- delimiter", eol };
	const end = content.indexOf(close, open.length);
	if (end === -1) return { frontmatter: "", body: content, error: "no closing --- delimiter", eol };
	return {
		frontmatter: content.slice(open.length, end),
		body: content.slice(end + close.length),
		eol,
	};
}

function scalarValue(frontmatter: string, key: string): { value: string; lineIndex: number; block?: boolean } {
	const lines = frontmatter.split(/\r?\n/);
	for (let i = 0; i < lines.length; i++) {
		const m = lines[i].match(new RegExp(`^${key}:\\s*(.*)$`));
		if (m) {
			const raw = m[1].trim();
			if (raw === "|" || raw === ">" || raw.startsWith("|-") || raw.startsWith(">-") || raw === "") {
				return { value: "", lineIndex: i, block: true };
			}
			return { value: raw.replace(/^["']|["']$/g, ""), lineIndex: i };
		}
	}
	return { value: "", lineIndex: -1 };
}

function stripFields(frontmatter: string): { patched: string; stripped: string[]; warnings: string[] } {
	const lines = frontmatter.split(/\r?\n/);
	const out: string[] = [];
	const stripped: string[] = [];
	const warnings: string[] = [];
	let skipBlockUntilIndent = -1;
	for (let i = 0; i < lines.length; i++) {
		if (skipBlockUntilIndent >= 0) {
			const line = lines[i];
			if (line.trim() === "" || line.startsWith(" ") || line.startsWith("\t")) {
				continue; // still inside the stripped block scalar
			}
			skipBlockUntilIndent = -1;
		}
		const m = lines[i].match(/^(sha256|signature|signed_by):\s*(.*)$/);
		if (m) {
			stripped.push(lines[i]);
			const rest = m[2].trim();
			if (rest === "|" || rest === ">" || rest === "|-" || rest === ">-" || rest === "") {
				// Block scalar or empty: swallow following indented lines.
				skipBlockUntilIndent = i;
				if (rest !== "") warnings.push(`field '${m[1]}' is a block scalar (line ${i + 1}); block lines dropped`);
			}
			continue;
		}
		out.push(lines[i]);
	}
	return { patched: out.join("\n"), stripped, warnings };
}

function walkSkillFiles(src: string): string[] {
	const found: string[] = [];
	const root = readdirSync(src, { withFileTypes: true });
	for (const entry of root) {
		if (entry.isDirectory()) {
			if (entry.name === "WEB") {
				const webRoot = join(src, "WEB", "OWASP_WSTG_4.2");
				if (!existsSync(webRoot)) throw new Error(`expected WEB/OWASP_WSTG_4.2 under ${src}`);
				const walk = (dir: string) => {
					for (const e of readdirSync(dir, { withFileTypes: true })) {
						const full = join(dir, e.name);
						if (e.isDirectory()) walk(full);
						else if (e.name === "SKILL.md") found.push(full);
					}
				};
				walk(webRoot);
			} else if (entry.name.startsWith("attack-") || entry.name === "recon-methodology") {
				const skill = join(src, entry.name, "SKILL.md");
				if (existsSync(skill)) found.push(skill);
			}
		}
	}
	return found;
}

function portSkill(skillFile: string, src: string, dst: string, seen: Map<string, string>): PortedSkill {
	const content = readFileSync(skillFile, "utf8");
	const { frontmatter, body, error, eol } = splitFrontmatter(content);
	if (error) throw new Error(`${skillFile}: ${error}`);
	const dirName = basename(dirname(skillFile));

	const nameInfo = scalarValue(frontmatter, "name");
	if (nameInfo.lineIndex === -1) throw new Error(`${skillFile}: missing 'name' in frontmatter`);
	if (nameInfo.value !== dirName) {
		throw new Error(`${skillFile}: frontmatter name '${nameInfo.value}' != directory name '${dirName}'`);
	}
	if (seen.has(nameInfo.value)) {
		throw new Error(`duplicate skill name '${nameInfo.value}' in ${skillFile} and ${seen.get(nameInfo.value)}`);
	}
	seen.set(nameInfo.value, skillFile);

	const descInfo = scalarValue(frontmatter, "description");
	if (descInfo.lineIndex === -1 || descInfo.value === "") {
		throw new Error(`${skillFile}: missing or empty 'description' in frontmatter`);
	}
	if (descInfo.block) throw new Error(`${skillFile}: description is a block scalar; port script expects single-line`);

	const categoryInfo = scalarValue(frontmatter, "category");
	const owaspInfo = scalarValue(frontmatter, "owasp_id");

	const { patched, stripped, warnings } = stripFields(frontmatter);
	if (stripped.length > 0) warnings.push(`stripped fields: ${stripped.join(" | ")}`);

	// Copy any extra files inside the skill dir (warn, keep layout).
	const skillDir = dirname(skillFile);
	const extraFiles: string[] = [];
	for (const e of readdirSync(skillDir, { withFileTypes: true })) {
		if (e.name === "SKILL.md") continue;
		extraFiles.push(e.name);
	}

	const outDir = join(dst, dirName);
	mkdirSync(outDir, { recursive: true });
	writeFileSync(join(outDir, "SKILL.md"), `---${eol}hide: true${eol}${patched}${eol}---${eol}${body}`);
	for (const extra of extraFiles) {
		const full = join(skillDir, extra);
		copyFileSync(full, join(outDir, extra));
	}
	for (const w of warnings) console.warn(`WARN ${skillFile}: ${w}`);

	return {
		name: nameInfo.value,
		description: descInfo.value,
		dir: outDir,
		category: categoryInfo.value || (dirName.startsWith("attack-") ? "web-application" : ""),
		owaspId: owaspInfo.value,
		sourceRel: relative(src, skillFile),
		extraFiles,
	};
}

const WSTG_FAMILY_ORDER = [
	["info", "Information Gathering"],
	["conf", "Configuration and Deployment"],
	["idnt", "Identity Management"],
	["athn", "Authentication"],
	["sess", "Session Management"],
	["authz", "Authorization"],
	["inpv", "Input Validation"],
	["busl", "Business Logic"],
	["clnt", "Client-side"],
	["cryp", "Cryptography"],
	["errh", "Error Handling"],
	["apit", "API Testing"],
] as const;

function renderIndex(skills: PortedSkill[], src: string): string {
	const lines: string[] = [];
	lines.push("# Web Pentest Skill Index (ported from CyberStrike)");
	lines.push("");
	lines.push(`Source: \`${src}\` (see ATTRIBUTION.md for provenance and license).`);
	lines.push("");
	lines.push("Each skill is loaded on demand via the `read` tool (`path: \"skill://<name>\"`; `skill://` is a read-path, never a tool name). The `web-pentest`");
	lines.push("umbrella skill maps every phase to the relevant skills below.");
	lines.push("");
	lines.push("## WSTG 4.2 families");
	lines.push("");
	let total = 0;
	for (const [prefix, label] of WSTG_FAMILY_ORDER) {
		const members = skills.filter(s => s.name.startsWith(`wstg-${prefix}`));
		if (members.length === 0) continue;
		lines.push(`### ${label} (${prefix})`);
		lines.push("");
		lines.push("| Skill | WSTG | Description |");
		lines.push("|---|---|---|");
		for (const s of members.sort((a, b) => a.name.localeCompare(b.name))) {
			lines.push(`| \`skill://${s.name}\` | ${s.owaspId || "—"} | ${s.description.replace(/\|/g, "\\|")} |`);
			total++;
		}
		lines.push("");
	}
	lines.push("### Composite umbrellas");
	lines.push("");
	lines.push("| Skill | Description |");
	lines.push("|---|---|");
	for (const s of skills.filter(s =>
		["wstg-injection", "wstg-auth-session", "wstg-logic-client-api", "wstg-recon-config"].includes(s.name),
	)) {
		lines.push(`| \`skill://${s.name}\` | ${s.description.replace(/\|/g, "\\|")} |`);
		total++;
	}
	lines.push("");
	lines.push("## Attack playbooks");
	lines.push("");
	lines.push("| Skill | Description |");
	lines.push("|---|---|");
	for (const s of skills.filter(s => s.name.startsWith("attack-")).sort((a, b) => a.name.localeCompare(b.name))) {
		lines.push(`| \`skill://${s.name}\` | ${s.description.replace(/\|/g, "\\|")} |`);
		total++;
	}
	lines.push("");
	lines.push("## Recon methodology");
	lines.push("");
	lines.push("| Skill | Description |");
	lines.push("|---|---|");
	for (const s of skills.filter(s => s.name === "recon-methodology")) {
		lines.push(`| \`skill://${s.name}\` | ${s.description.replace(/\|/g, "\\|")} |`);
		total++;
	}
	lines.push("");
	lines.push(`Total: ${total} skills.`);
	lines.push("");
	return lines.join("\n");
}

function gitCommit(repoDir: string): string {
	try {
		return execSync(`git -C "${repoDir}" rev-parse HEAD`, { encoding: "utf8" }).trim();
	} catch {
		return "unknown";
	}
}

function main(argv: readonly string[]): void {
	const { src, dst } = parseArgs(argv);
	mkdirSync(dst, { recursive: true });

	const skillFiles = walkSkillFiles(src);
	if (skillFiles.length === 0) throw new Error(`no SKILL.md files found under ${src}`);
	const seen = new Map<string, string>();
	const skills = skillFiles.map(f => portSkill(f, src, dst, seen));
	skills.sort((a, b) => a.name.localeCompare(b.name));

	// Scanners → <pentestRoot>/scanners.
	const csRoot = dirname(dirname(src)); // skill → .cyberstrike → repo root
	const scannersSrc = join(csRoot, "packages", "cyberstrike", "data", "scripts");
	const pentestRoot = dirname(dst); // src/pentest (INDEX.md/ATTRIBUTION.md/scanners live here)
	const scannersDst = join(pentestRoot, "scanners");
	mkdirSync(scannersDst, { recursive: true });
	let copiedScanners = 0;
	for (const name of SCANNER_NAMES) {
		const from = join(scannersSrc, `${name}.py`);
		if (!existsSync(from)) {
			console.warn(`WARN scanner not found: ${from}`);
			continue;
		}
		copyFileSync(from, join(scannersDst, `${name}.py`));
		copiedScanners++;
	}

	// INDEX.md + ATTRIBUTION.md at the pentest root AND inside the umbrella
	// skill dir (so skill://web-pentest/INDEX.md resolves for workers).
	writeFileSync(join(pentestRoot, "INDEX.md"), renderIndex(skills, src));
	const commit = gitCommit(csRoot); // CyberStrike repo root
	const attribution = `# Attribution & Licensing — ported Web Pentest content

This directory (packages/coding-agent/src/pentest) contains skills under
\`skills/<name>/SKILL.md\` (one-level layout, \`hide: true\` on every ported skill)
and the 16 attack scanners under \`scanners/\`. Generated from the **CyberStrike**
repository:

- Upstream: https://github.com/CyberStrikeus/CyberStrike
- Fork used: https://github.com/shantanu561993/CyberStrike (also attributed upstream)
- Source checkout commit: \`${commit}\`
- Port script: \`scripts/port-cyberstrike-skills.ts\` (OMP repo, MIT)

## Licenses

- **Ported skills and scanner scripts** are AGPL-3.0-only (CyberStrike LICENSE).
  WSTG-derived skill content is OWASP WSTG 4.2 material (CC BY-SA 4.0) as
  distributed inside CyberStrike.
- **The Bolt client** (packages/coding-agent/src/mcp/bolt.ts + tools/bolt.ts,
  \`bolt\`/\`bolt_status\` tools) is a protocol port of AGPL
  \`packages/cyberstrike/src/mcp/bolt-auth.ts\` (AGPL-3.0); attribution headers
  in the sources.
- **The crawler package** (packages/hackbrowser/) vendors CyberStrike
  \`packages/hackbrowser\` source (AGPL-3.0); mechanical fixes (deepseek via
  OpenAI-compatible endpoint, node bundle for Playwright, session export,
  session-guardian bot) are listed in the lib attribution headers.
- **OMP-authored orchestration** (umbrella skill, commands, agent, methodology
  module, http_log/session_bot tools, this INDEX/ATTRIBUTION) is MIT like
  Oh My Pi.

## Redistribution

Ported content MUST NOT be upstreamed into \`can1357/oh-my-pi\` without relicensing.
`;
	writeFileSync(join(pentestRoot, "ATTRIBUTION.md"), attribution);
	// Mirror both into the umbrella skill dir so skill://web-pentest/INDEX.md
	// and skill://web-pentest/ATTRIBUTION.md resolve (workers read them there).
	const umbrellaDir = join(dst, "web-pentest");
	mkdirSync(umbrellaDir, { recursive: true });
	writeFileSync(join(umbrellaDir, "INDEX.md"), renderIndex(skills, src));
	writeFileSync(join(umbrellaDir, "ATTRIBUTION.md"), attribution);

	console.log(`Ported ${skills.length} skills from ${src} to ${dst}`);
	console.log(
		`  WSTG: ${skills.filter(s => s.name.startsWith("wstg-")).length}, attack: ${skills.filter(s => s.name.startsWith("attack-")).length}, recon: ${skills.filter(s => s.name === "recon-methodology").length}`,
	);
	console.log(`Copied ${copiedScanners} scanners to ${scannersDst}`);
	console.log(`Wrote ${join(pentestRoot, "INDEX.md")} and ${join(pentestRoot, "ATTRIBUTION.md")}`);
	console.log(`Source commit: ${commit}`);
	const extraTotal = skills.filter(s => s.extraFiles.length > 0).length;
	if (extraTotal > 0) console.warn(`WARN ${extraTotal} skill dirs had extra files (copied along)`);
}

try {
	main(process.argv.slice(2));
} catch (err) {
	console.error(`ERROR: ${(err as Error).message}`);
	process.exit(1);
}
